-- CREATING A NEW DATABASE
CREATE DATABASE SUB_LANGUAGES;
-- USING THE EXISTING DATABASE TO CREATE A TABLE.
USE SUB_LANGUAGES;
-- CREATING A NEW TABLE FOR STUDENTS
CREATE TABLE STUDENTS(
STD_ID TINYINT UNSIGNED PRIMARY KEY,
NAME VARCHAR(30) UNIQUE NOT NULL,
AGE TINYINT UNSIGNED,
SUBJECT VARCHAR(30));

-- ADDING ANOTHER COLUMN INTO THE STUDENTS TABLE
ALTER TABLE STUDENTS ADD MARKS TINYINT UNSIGNED;
ALTER TABLE DA_DS_STUDENTS MODIFY STD_ID TINYINT UNSIGNED AUTO_INCREMENT;

-- BY USING DROP COMMAND WE CAN DELETE ENTIRE TABLE OR A COLUMN IN A TABLE
-- IF WE WANT TO DELETE ENTIRE TABLE MEANS - DROP TABLE STUDENTS;
-- IF WE WANT TO DELETE A COLUMN FROM STUDENTS MEANS:
ALTER TABLE STUDENTS DROP COLUMN AGE;
-- TRUNCATE COMMAND DELETES THE COMPLETE DATA INSIDE TABLE BUT STRUCTURE REMAINS SAME - TRUNCATE TABLE STUDENTS;
-- RENAMEING THE TABLE NAME
RENAME TABLE STUDENTS TO DA_DS_STUDENTS;

SELECT * FROM DA_DS_STUDENTS;

-- ADDING RECORDS INTO THE TABLE
INSERT INTO DA_DS_STUDENTS(NAME,SUBJECT,MARKS) VALUES
("VISHNU","DS",88),
("SAMAIRA","DS",79),
("PRASANNA","DA",85),
("AKSHAYA","DA",60),
("KEERTHANA","DS",65),
("LAKSHMI","DA",80),
("SAI","DS",69);
-- UPDATING A VALUES IN THE STUDENTS RECORDS
UPDATE DA_DS_STUDENTS SET MARKS = 78
WHERE NAME = "VISHNU";

-- REMOVING ONE RECORD FROM THE TABLE
DELETE FROM DA_DS_STUDENTS
WHERE NAME = "SAI";

-- FETCHING THE DATA FROM THE DA_DS_STUDENTS TABLE
SELECT * FROM DA_DS_STUDENTS;
